# image will be published to ghcr.io/<user>/<name>
name: kinoite-custom-intel
# description will be included in the image's metadata
description: Imagen customizada de Fedora Kinoite, para su uso en mi Dell Optiplex (Intel CPU + GPU)
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39 # latest is also supported if you want new updates ASAP
# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
        #
        # copies config/files/usr into your image's /usr
        #
        # configuration you wish to end up in /etc/ on the booted system
        # should be added into /usr/etc/ as that is the proper "distro"
        # config directory on ostree. Read more in the files module's README
  - type: rpm-ostree
    repos:
    # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - igt-gpu-tools
      - lm_sensors
      - neofetch
      - hunspell-es
      - hunspell-es-CL
      - gnome-disk-utility
      - steam-devices
      - gcc
      - VirtualBox
      - kvantum
      - okular
      - gwenview

    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - google-noto-sans-cjk-fonts
      - google-noto-sans-javanese-fonts
      - google-noto-sans-balinese-fonts
      - google-noto-sans-sundanese-fonts
      - google-noto-naskh-arabic-vf-fonts
      - google-noto-sans-arabic-vf-fonts
      - google-noto-sans-armenian-vf-fonts
      - google-noto-sans-bengali-vf-fonts
      - google-noto-sans-canadian-aboriginal-vf-fonts
      - google-noto-sans-cherokee-vf-fonts
      - google-noto-sans-devanagari-vf-fonts
      - google-noto-sans-ethiopic-vf-fonts
      - google-noto-sans-georgian-vf-fonts
      - google-noto-sans-gujarati-vf-fonts
      - google-noto-sans-gurmukhi-vf-fonts
      - google-noto-sans-hebrew-vf-fonts
      - google-noto-sans-kannada-vf-fonts
      - google-noto-sans-khmer-vf-fonts
      - google-noto-sans-lao-vf-fonts
      - google-noto-sans-mono-cjk-vf-fonts
      - google-noto-sans-oriya-vf-fonts
      - google-noto-sans-sinhala-vf-fonts
      - google-noto-sans-tamil-vf-fonts
      - google-noto-sans-telugu-vf-fonts
      - google-noto-sans-thaana-vf-fonts
      - google-noto-sans-thai-vf-fonts
      - google-noto-serif-armenian-vf-fonts
      - google-noto-serif-bengali-vf-fonts
      - google-noto-serif-cjk-vf-fonts
      - google-noto-serif-devanagari-vf-fonts
      - google-noto-serif-georgian-vf-fonts
      - google-noto-serif-gujarati-vf-fonts
      - google-noto-serif-gurmukhi-vf-fonts
      - google-noto-serif-hebrew-vf-fonts
      - google-noto-serif-kannada-vf-fonts
      - google-noto-serif-khmer-vf-fonts
      - google-noto-serif-lao-vf-fonts
      - google-noto-serif-oriya-vf-fonts
      - google-noto-serif-sinhala-vf-fonts
      - google-noto-serif-tamil-vf-fonts
      - google-noto-serif-telugu-vf-fonts
      - google-noto-serif-thai-vf-fonts
      - default-fonts-cjk-mono
      - default-fonts-am
      - default-fonts-ar
      - default-fonts-as
      - default-fonts-ast
      - default-fonts-be
      - default-fonts-bg
      - default-fonts-bn
      - default-fonts-bo
      - default-fonts-br
      - default-fonts-chr
      - default-fonts-cjk-serif
      - default-fonts-dv
      - default-fonts-dz
      - default-fonts-el
      - default-fonts-eo
      - default-fonts-eu
      - default-fonts-fa
      - default-fonts-gu
      - default-fonts-he
      - default-fonts-hi
      - default-fonts-hy
      - default-fonts-ia
      - default-fonts-iu
      - default-fonts-ka
      - default-fonts-km
      - default-fonts-kn
      - default-fonts-ku
      - default-fonts-lo
      - default-fonts-mai
      - default-fonts-ml
      - default-fonts-mr
      - default-fonts-my
      - default-fonts-nb
      - default-fonts-ne
      - default-fonts-nn
      - default-fonts-nr
      - default-fonts-nso
      - default-fonts-or
      - default-fonts-pa
      - default-fonts-ru
      - default-fonts-si
      - default-fonts-ss
      - default-fonts-ta
      - default-fonts-te
      - default-fonts-th
      - default-fonts-tn
      - default-fonts-ts
      - default-fonts-uk
      - default-fonts-ur
      - default-fonts-ve
      - default-fonts-vi
      - default-fonts-xh
      - default-fonts-yi
      - default-fonts-zu
      - jomolhari-fonts
      - default-fonts-other-sans
      - default-fonts-other-serif
      - nvidia-gpu-firmware
      - amd-ucode-firmware
      - libratbag-ratbagd
      - xwaylandvideobridge
      - mozilla-filesystem
      - mozilla-openh264
      - nvtop



  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - justfiles # add "!include /usr/share/ublue-os/just/100-bling.just"
      # in your custom.just (added by default) or local justfile
      - nix-installer # shell shortcuts for determinate system's nix installers
      - ublue-os-wallpapers
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - 1password # install 1Password (stable) and `op` CLI tool
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm
      # - gnome-vrr # enables gnome-vrr for your image
      # - container-tools # installs container-related tools onto /usr/bin: kind, kubectx, docker-compose and kubens
      # - laptop # installs TLP and configures your system for laptop usage
      # - flatpaksync # allows synchronization of user-installed flatpaks, see separate documentation section
  - type: yafti # if included, yafti and it's dependencies (pip & libadwaita)
    #  will be installed and set up
    custom-flatpaks: # this section is optional
    # - Celluloid: io.github.celluloid_player.Celluloid
    # - Krita: org.kde.krita
  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
